### ISSUE TITLE
Ticking Entity crash upon wearing boots

### ISSUE THREAD

**Issue by KreativeKngYT** [Alastors/ThaumicBoots#37]
[crash-2024-06-01_07.03.56-client.txt](https://github.com/user-attachments/files/15522075/crash-2024-06-01_07.03.56-client.txt)

Any time I put on boots not from you mod, it crashes the game with a ticking player entity crash. its somehow related to your mod. I link the crash report in this post for you to look at. I simple but on some Iron Boots, walked a few steps and it crashed and now i crash upon trying to rejoin the world.

**Comment by penguin-glitch** [comment]
Seconding this - seems to be related to the electric comet boots (which is a GTNH thing, right? wonder if references to it got merged by mistake): 
Caused by: java.lang.NoClassDefFoundError: thaumicboots/item/boots/comet/ItemElectricCometBoots
	at thaumicboots.events.BootsEventHandler.onLivingFall(BootsEventHandler.java:113) ~[BootsEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1001_BootsEventHandler_onLivingFall_LivingFallEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingFall(ForgeHooks.java:314) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70069_a(EntityLivingBase.java:1004) ~[sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70069_a(EntityPlayer.java:1776) ~[yz.class:?]
	at net.minecraft.entity.Entity.func_70064_a(Entity.java:916) ~[sa.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70064_a(EntityLivingBase.java:182) ~[sv.class:?]
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:738) ~[sa.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1490) ~[sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70612_e(EntityPlayer.java:1656) ~[yz.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1814) ~[sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:540) ~[yz.class:?]
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:287) ~[blk.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611) ~[sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[yz.class:?]
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63) ~[bjk.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2070) ~[ahb.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2034) ~[ahb.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1887) ~[ahb.class:?]

**Comment by Sunconure11** [comment]
@Alastors
